In [109]:
!pip install opendatasets
import opendatasets as od
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

Requirement already satisfied: opendatasets in /usr/local/lib/python3.11/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from opendatasets) (8.1.8)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2024.12.14)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.3.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.11/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.10)

In [110]:
datasetlink = "https://www.kaggle.com/datasets/pranalibose/amazon-seller-order-status-prediction"
od.download(datasetlink)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: kidkeozz
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/pranalibose/amazon-seller-order-status-prediction
Downloading amazon-seller-order-status-prediction.zip to ./amazon-seller-order-status-prediction

100%|██████████| 23.4k/23.4k [00:00<00:00, 8.70MB/s]

In [111]:
os.chdir("amazon-seller-order-status-prediction")
os.listdir()

['orders_data.xlsx']

##Visualizar filas del dataset

In [112]:
archivo = 'orders_data.xlsx'
df = pd.read_excel(archivo, engine='openpyxl') # Use pd.read_excel with the 'openpyxl' engine.
df.head()

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
0,405-9763961-5211537,"Sun, 18 Jul, 2021, 10:38 pm IST",Mr.,"CHANDIGARH,",CHANDIGARH,SKU: 2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,₹449.00,NaN,NaN,Delivered to buyer
1,404-3964908-7850720,"Tue, 19 Oct, 2021, 6:05 pm IST",Minam,"PASIGHAT,",ARUNACHAL PRADESH,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,₹60.18,NaN,Delivered to buyer
2,171-8103182-4289117,"Sun, 28 Nov, 2021, 10:20 pm IST",yatipertin,"PASIGHAT,",ARUNACHAL PRADESH,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,₹60.18,NaN,Delivered to buyer
3,405-3171677-9557154,"Wed, 28 Jul, 2021, 4:06 am IST",aciya,"DEVARAKONDA,",TELANGANA,SKU: AH-J3AO-R7DN,Pure 100% Leather Block Print Rectangular Jewe...,1,NaN,NaN,Cash On Delivery,Delivered to buyer
4,402-8910771-1215552,"Tue, 28 Sept, 2021, 2:50 pm IST",Susmita,"MUMBAI,",MAHARASHTRA,SKU: KL-7WAA-Z82I,Pure Leather Sling Bag with Multiple Pockets a...,1,"₹1,099.00",₹84.96,NaN,Delivered to buyer

In [113]:
df.tail()

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
166,171-2829978-1258758,"Mon, 13 Dec, 2021, 11:30 am IST",Shahin,"MUMBAI,",MAHARASHTRA,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,3,"₹1,347.00",₹84.96,Cash On Delivery,Delivered to buyer
167,402-3045457-5360311,"Wed, 1 Dec, 2021, 12:18 pm IST",Sharmistha,"DEHRADUN,",UTTARAKHAND,SKU: SB-WDQN-SDN9,Traditional Block-Printed Women's 100% Pure Le...,1,"₹1,299.00",₹114.46,NaN,Delivered to buyer
168,408-2260162-8323567,"Thu, 9 Dec, 2021, 6:55 pm IST",shashank,"Durg,",CHHATTISGARH,SKU: SB-WDQN-SDN9,Traditional Block-Printed Women's 100% Pure Le...,1,"₹1,299.00",₹105.02,NaN,Delivered to buyer
169,403-5664951-8941100,"Wed, 23 Feb, 2022, 12:43 am IST",Jayeta,"KOLKATA,",WEST BENGAL,SKU: N8-YFZF-P74I,Stylish and Sleek Multiple Pockets 100 Percent...,1,"₹1,499.00",₹80.24,Cash On Delivery,Delivered to buyer
170,402-4845680-8041921,"Sun, 26 Dec, 2021, 6:21 pm IST",Varun,"MUMBAI,",MAHARASHTRA,SKU: 2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,₹449.00,₹84.96,NaN,Delivered to buyer

In [114]:
df.sample(5)

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
105,404-3361026-0027538,"Mon, 29 Nov, 2021, 6:09 pm IST",Sayanti,"NOIDA,",UTTAR PRADESH,SKU: 7K-6YIU-KO0R,Women's Pure Leather Jhallar Clutch Purse with...,1,₹399.00,₹84.96,NaN,Delivered to buyer
154,171-4338001-7654754,"Sun, 9 Jan, 2022, 9:33 pm IST",srisoma,"NEW DELHI,",DELHI,SKU: U1-8YOK-510E,100% Leather Cat Shaped Piggy Coin Bank | Bloc...,1,₹449.00,₹84.96,NaN,Delivered to buyer
52,404-7918321-6528342,"Wed, 16 Jun, 2021, 8:53 pm IST",narendra,"KODAD,",TELANGANA,SKU: 5B-NW9K-L3AO,Pure Leather Elephant Shaped Piggy Coin Bank |...,1,₹175.00,NaN,Cash On Delivery,Delivered to buyer
5,406-9292208-6725123,"Thu, 17 Jun, 2021, 9:12 pm IST",Subinita,"HOWRAH,",WEST BENGAL,SKU: HH-FOWV-5YWO,Women's Trendy Pure Leather Clutch Purse | Lea...,1,₹200.00,NaN,NaN,Delivered to buyer
142,402-3108828-3083537,"Wed, 29 Dec, 2021, 8:44 am IST",RAJAT,PUNJAB,"MOHALI,",SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,₹84.96,Cash On Delivery,Delivered to buyer

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_no      171 non-null    object
 1   order_date    171 non-null    object
 2   buyer         171 non-null    object
 3   ship_city     171 non-null    object
 4   ship_state    171 non-null    object
 5   sku           171 non-null    object
 6   description   171 non-null    object
 7   quantity      171 non-null    int64
 8   item_total    153 non-null    object
 9   shipping_fee  145 non-null    object
 10  cod           47 non-null     object
 11  order_status  171 non-null    object
dtypes: int64(1), object(11)
memory usage: 16.2+ KB

In [116]:
fs=df.shape
print('Original shape : {}'.format(fs))

df = df.drop_duplicates()

ns= df.shape
print('There were {} duplicates'.format((fs[0])-(ns[0])))
print('New shape : {}'.format(ns))

Original shape : (171, 12)
There were 0 duplicates
New shape : (171, 12)

##Analisis del dataset

In [117]:
df.describe()

         quantity
count  171.000000
mean     1.087719
std      0.445132
min      1.000000
25%      1.000000
50%      1.000000
75%      1.000000
max      4.000000

In [118]:
df.describe(include='object')

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: FutureWarning: Parsed string "Sun, 18 Jul, 2021, 10:38 pm IST" included an un-recognized timezone "IST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,order_no,order_date,buyer,ship_city,ship_state,sku,description,item_total,shipping_fee,cod,order_status
count,171,171,171,171,171,171,171,153,145,47,171
unique,171,171,149,81,30,54,61,18,13,1,2
top,405-9763961-5211537,"Sun, 18 Jul, 2021, 10:38 pm IST",Geetika,"MUMBAI,",MAHARASHTRA,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,₹449.00,₹84.96,Cash On Delivery,Delivered to buyer
freq,1,1,3,17,31,33,33,52,100,47,160

In [119]:
df.nunique()

order_no        171
order_date      171
buyer           149
ship_city        81
ship_state       30
sku              54
description      61
quantity          4
item_total       18
shipping_fee     13
cod               1
order_status      2
dtype: int64

In [120]:
df.isnull().sum()

order_no          0
order_date        0
buyer             0
ship_city         0
ship_state        0
sku               0
description       0
quantity          0
item_total       18
shipping_fee     26
cod             124
order_status      0
dtype: int64

In [121]:
numero_registros = np.product(df.shape)

suma_nulos = df.isnull().sum().sum()

porcentaje_nulos = (suma_nulos / numero_registros) * 100

print(f"El DataFrame tiene un {porcentaje_nulos:.2f}% de valores nulos. que son {suma_nulos} registros")

El DataFrame tiene un 8.19% de valores nulos. que son 168 registros

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_no      171 non-null    object
 1   order_date    171 non-null    object
 2   buyer         171 non-null    object
 3   ship_city     171 non-null    object
 4   ship_state    171 non-null    object
 5   sku           171 non-null    object
 6   description   171 non-null    object
 7   quantity      171 non-null    int64
 8   item_total    153 non-null    object
 9   shipping_fee  145 non-null    object
 10  cod           47 non-null     object
 11  order_status  171 non-null    object
dtypes: int64(1), object(11)
memory usage: 16.2+ KB

In [123]:
df.sample(2)

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
119,406-6970801-9059504,"Wed, 1 Dec, 2021, 7:12 pm IST",Rebecca,"Bardez,",GOA,SKU: CR-6E69-UXFW,Bright and Colorful Shantiniketan Leather Elep...,1,₹449.00,₹84.96,NaN,Delivered to buyer
100,407-9473791-2643568,"Fri, 25 Feb, 2022, 12:04 am IST",chandrima,"KATWA,",WEST BENGAL,SKU: P1-LF2X-L3ZC,Colourful and Bright Peacock Shaped Piggy Coin...,1,₹449.00,₹60.18,NaN,Delivered to buyer

In [124]:
df.dtypes

order_no        object
order_date      object
buyer           object
ship_city       object
ship_state      object
sku             object
description     object
quantity         int64
item_total      object
shipping_fee    object
cod             object
order_status    object
dtype: object

In [125]:
from dateutil import parser

fecha_str = "Sat, 4 Sept, 2021, 11:53 am IST"
fecha = parser.parse(fecha_str)
print(fecha)  # Output: 2021-09-04 11:53:00+05:30 (si IST = India Standard Time)

2021-09-04 11:53:00

/usr/local/lib/python3.11/dist-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname IST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [126]:
!pip install pendulum
import pendulum

fecha_str = "Sat, 4 Sept, 2021, 11:53 am IST"
fecha = pendulum.parse(fecha_str, strict=False)
print(fecha)  # Output: 2021-09-04T11:53:00+05:30 (si IST = Asia/Kolkata)

Requirement already satisfied: pendulum in /usr/local/lib/python3.11/dist-packages (3.0.0)
Requirement already satisfied: python-dateutil>=2.6 in /usr/local/lib/python3.11/dist-packages (from pendulum) (2.8.2)
Requirement already satisfied: tzdata>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pendulum) (2025.1)
Requirement already satisfied: time-machine>=2.6.0 in /usr/local/lib/python3.11/dist-packages (from pendulum) (2.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.6->pendulum) (1.17.0)
2021-09-04 11:53:00+00:00

In [127]:
df['order_date'] = df['order_date'].apply(lambda x: pendulum.parse(x, strict=False))
df.head(2)

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
0,405-9763961-5211537,2021-07-18 22:38:00+00:00,Mr.,"CHANDIGARH,",CHANDIGARH,SKU: 2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,₹449.00,NaN,NaN,Delivered to buyer
1,404-3964908-7850720,2021-10-19 18:05:00+00:00,Minam,"PASIGHAT,",ARUNACHAL PRADESH,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,₹60.18,NaN,Delivered to buyer

In [128]:
df.dtypes

order_no                     object
order_date      datetime64[ns, UTC]
buyer                        object
ship_city                    object
ship_state                   object
sku                          object
description                  object
quantity                      int64
item_total                   object
shipping_fee                 object
cod                          object
order_status                 object
dtype: object

In [129]:
df[["buyer", "ship_city", "ship_state", "sku", "description", "order_status"]] = df[["buyer", "ship_city", "ship_state", "sku", "description", "order_status"]].fillna("").astype("string")
df.head(2)

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
0,405-9763961-5211537,2021-07-18 22:38:00+00:00,Mr.,"CHANDIGARH,",CHANDIGARH,SKU: 2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,₹449.00,NaN,NaN,Delivered to buyer
1,404-3964908-7850720,2021-10-19 18:05:00+00:00,Minam,"PASIGHAT,",ARUNACHAL PRADESH,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,₹60.18,NaN,Delivered to buyer

In [130]:
df.dtypes

order_no                     object
order_date      datetime64[ns, UTC]
buyer                string[python]
ship_city            string[python]
ship_state           string[python]
sku                  string[python]
description          string[python]
quantity                      int64
item_total                   object
shipping_fee                 object
cod                          object
order_status         string[python]
dtype: object

In [131]:
df['cod'].value_counts()

cod
Cash On Delivery    47
Name: count, dtype: int64

In [132]:
df['cod'].fillna('unspecified', inplace=True)

<ipython-input-132-fed7925ac3f3>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cod'].fillna('unspecified', inplace=True)

In [133]:
df['cod'].value_counts()

cod
unspecified         124
Cash On Delivery     47
Name: count, dtype: int64

In [134]:
df.isnull().sum()

order_no         0
order_date       0
buyer            0
ship_city        0
ship_state       0
sku              0
description      0
quantity         0
item_total      18
shipping_fee    26
cod              0
order_status     0
dtype: int64

In [135]:
df[df["item_total"].isnull()]

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
3,405-3171677-9557154,2021-07-28 04:06:00+00:00,aciya,"DEVARAKONDA,",TELANGANA,SKU: AH-J3AO-R7DN,Pure 100% Leather Block Print Rectangular Jewe...,1,NaN,NaN,Cash On Delivery,Delivered to buyer
6,404-5794317-7737924,2021-08-12 20:03:00+00:00,shailendra,"ORAI,",UTTAR PRADESH,SKU: TQ-OE6K-9DIK,Ultra Slim 100% Pure Leather Men's Wallet with...,1,NaN,NaN,Cash On Delivery,Returned to seller
14,408-9557300-6760347,2021-10-14 23:14:00+00:00,Satish,"MANTHA,",MAHARASHTRA,SKU: YJ-5CCT-M3PP,Pure Leather Camel Color Gent's Wallet with Co...,1,NaN,₹84.96,Cash On Delivery,Returned to seller
22,171-6105173-4790734,2021-11-26 19:22:00+00:00,Geetika,"GURUGRAM,",HARYANA,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Returned to seller
24,403-7876698-8356365,2021-06-25 07:48:00+00:00,Yash,"MUMBAI,",MAHARASHTRA,SKU: 3O-GBSM-TYZE,100% Leather Ganesh Ji Piggy Coin Bank | Block...,1,NaN,NaN,Cash On Delivery,Returned to seller
39,404-8031085-1381943,2021-11-26 21:12:00+00:00,Kangana,"NEW DELHI,",DELHI,SKU: 54-D265-B74K,Set of 2 Pure Leather Block Print Round Jewelr...,4,NaN,₹84.96,unspecified,Returned to seller
43,405-8481932-1229966,2021-10-31 11:38:00+00:00,Amala,"KOLKATA,",WEST BENGAL,SKU: S1-A92Q-JU3X,100% Pure Leather Shantiniketan Clutch Purse: ...,1,NaN,₹47.20,unspecified,Returned to seller
47,405-1981073-5970737,2021-10-05 20:53:00+00:00,Jitu,"GUWAHATI,",ASSAM,SKU: I1-AWVT-2QOL,Women's Pure Leather Jhallar Clutch Purse with...,1,NaN,₹60.18,Cash On Delivery,Returned to seller
64,406-9458224-2717157,2021-11-09 23:23:00+00:00,Pooja,"GURUGRAM,",HARYANA,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Delivered to buyer
87,403-4274611-4049927,2021-10-07 11:23:00+00:00,Pooja,"SAHARANPUR,",UTTAR PRADESH,SKU: UR-WJJ0-I3TN,Pure 100% Leather Block Print Rectangular Jewe...,1,NaN,₹84.96,unspecified,Delivered to buyer
96,406-9977841-6948310,2021-09-16 06:59:00+00:00,Pramod,"GAUTAM BUDDHA NAGAR,",UTTAR PRADESH,SKU: 0M-RFE6-443C,Set of 2 Pure Leather Block Print Round Jewelr...,1,NaN,₹84.96,unspecified,Delivered to buyer
106,408-1794879-4342714,2021-12-23 12:02:00+00:00,Apoorva,"BENGALURU,",KARNATAKA,SKU: PG-WS6J-89DG,Bright and Colorful Shantiniketan Leather Elep...,1,NaN,₹84.96,unspecified,Delivered to buyer
114,405-0209265-6273962,2022-01-23 09:37:00+00:00,Gargi,"Ernakulam,",KERALA,SKU: V6-KQJX-XGP2,Women's Pure Leather Jhallar Clutch Purse with...,1,NaN,₹84.96,unspecified,Returned to seller
115,403-0102354-2668323,2022-01-30 02:42:00+00:00,Jeevan,"HYDERABAD,",TELANGANA,SKU: 2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,NaN,₹84.96,Cash On Delivery,Delivered to buyer
134,171-3919731-3769907,2022-01-25 11:32:00+00:00,Deepali,"JODHPUR,",RAJASTHAN,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Returned to seller
150,405-7352232-5348320,2021-12-19 07:41:00+00:00,DIVYA,"BENGALURU,",KARNATAKA,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Returned to seller
155,408-5721047-6522728,2021-12-12 19:09:00+00:00,Ashna,"CHANDIGARH,",CHANDIGARH,SKU: DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Delivered to buyer
159,403-8215280-0912306,2022-01-30 13:37:00+00:00,Gita,"CHENNAI,",TAMIL NADU,SKU: CR-6E69-UXFW,Bright and Colorful Shantiniketan Leather Elep...,1,NaN,₹84.96,Cash On Delivery,Returned to seller

In [136]:
df["sku"] = df["sku"].str.replace(" ", "", regex=True)

In [137]:
df[df["item_total"].isnull() == True]

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
3,405-3171677-9557154,2021-07-28 04:06:00+00:00,aciya,"DEVARAKONDA,",TELANGANA,SKU:AH-J3AO-R7DN,Pure 100% Leather Block Print Rectangular Jewe...,1,NaN,NaN,Cash On Delivery,Delivered to buyer
6,404-5794317-7737924,2021-08-12 20:03:00+00:00,shailendra,"ORAI,",UTTAR PRADESH,SKU:TQ-OE6K-9DIK,Ultra Slim 100% Pure Leather Men's Wallet with...,1,NaN,NaN,Cash On Delivery,Returned to seller
14,408-9557300-6760347,2021-10-14 23:14:00+00:00,Satish,"MANTHA,",MAHARASHTRA,SKU:YJ-5CCT-M3PP,Pure Leather Camel Color Gent's Wallet with Co...,1,NaN,₹84.96,Cash On Delivery,Returned to seller
22,171-6105173-4790734,2021-11-26 19:22:00+00:00,Geetika,"GURUGRAM,",HARYANA,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Returned to seller
24,403-7876698-8356365,2021-06-25 07:48:00+00:00,Yash,"MUMBAI,",MAHARASHTRA,SKU:3O-GBSM-TYZE,100% Leather Ganesh Ji Piggy Coin Bank | Block...,1,NaN,NaN,Cash On Delivery,Returned to seller
39,404-8031085-1381943,2021-11-26 21:12:00+00:00,Kangana,"NEW DELHI,",DELHI,SKU:54-D265-B74K,Set of 2 Pure Leather Block Print Round Jewelr...,4,NaN,₹84.96,unspecified,Returned to seller
43,405-8481932-1229966,2021-10-31 11:38:00+00:00,Amala,"KOLKATA,",WEST BENGAL,SKU:S1-A92Q-JU3X,100% Pure Leather Shantiniketan Clutch Purse: ...,1,NaN,₹47.20,unspecified,Returned to seller
47,405-1981073-5970737,2021-10-05 20:53:00+00:00,Jitu,"GUWAHATI,",ASSAM,SKU:I1-AWVT-2QOL,Women's Pure Leather Jhallar Clutch Purse with...,1,NaN,₹60.18,Cash On Delivery,Returned to seller
64,406-9458224-2717157,2021-11-09 23:23:00+00:00,Pooja,"GURUGRAM,",HARYANA,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Delivered to buyer
87,403-4274611-4049927,2021-10-07 11:23:00+00:00,Pooja,"SAHARANPUR,",UTTAR PRADESH,SKU:UR-WJJ0-I3TN,Pure 100% Leather Block Print Rectangular Jewe...,1,NaN,₹84.96,unspecified,Delivered to buyer
96,406-9977841-6948310,2021-09-16 06:59:00+00:00,Pramod,"GAUTAM BUDDHA NAGAR,",UTTAR PRADESH,SKU:0M-RFE6-443C,Set of 2 Pure Leather Block Print Round Jewelr...,1,NaN,₹84.96,unspecified,Delivered to buyer
106,408-1794879-4342714,2021-12-23 12:02:00+00:00,Apoorva,"BENGALURU,",KARNATAKA,SKU:PG-WS6J-89DG,Bright and Colorful Shantiniketan Leather Elep...,1,NaN,₹84.96,unspecified,Delivered to buyer
114,405-0209265-6273962,2022-01-23 09:37:00+00:00,Gargi,"Ernakulam,",KERALA,SKU:V6-KQJX-XGP2,Women's Pure Leather Jhallar Clutch Purse with...,1,NaN,₹84.96,unspecified,Returned to seller
115,403-0102354-2668323,2022-01-30 02:42:00+00:00,Jeevan,"HYDERABAD,",TELANGANA,SKU:2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,NaN,₹84.96,Cash On Delivery,Delivered to buyer
134,171-3919731-3769907,2022-01-25 11:32:00+00:00,Deepali,"JODHPUR,",RAJASTHAN,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Returned to seller
150,405-7352232-5348320,2021-12-19 07:41:00+00:00,DIVYA,"BENGALURU,",KARNATAKA,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Returned to seller
155,408-5721047-6522728,2021-12-12 19:09:00+00:00,Ashna,"CHANDIGARH,",CHANDIGARH,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,NaN,₹84.96,unspecified,Delivered to buyer
159,403-8215280-0912306,2022-01-30 13:37:00+00:00,Gita,"CHENNAI,",TAMIL NADU,SKU:CR-6E69-UXFW,Bright and Colorful Shantiniketan Leather Elep...,1,NaN,₹84.96,Cash On Delivery,Returned to seller

In [138]:
df["item_total"]=df.groupby("sku")["item_total"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

<ipython-input-138-cdab32021dab>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["item_total"]=df.groupby("sku")["item_total"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))
<ipython-input-138-cdab32021dab>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["item_total"]=df.groupby("sku")["item_total"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

In [139]:
df["item_total"]=df.groupby("description")["item_total"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

<ipython-input-139-1555fa1a2775>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["item_total"]=df.groupby("description")["item_total"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))
<ipython-input-139-1555fa1a2775>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["item_total"]=df.groupby("description")["item_total"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

In [140]:
df.isnull().sum()

order_no         0
order_date       0
buyer            0
ship_city        0
ship_state       0
sku              0
description      0
quantity         0
item_total       3
shipping_fee    26
cod              0
order_status     0
dtype: int64

In [141]:
df[df["shipping_fee"].isnull()]

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
0,405-9763961-5211537,2021-07-18 22:38:00+00:00,Mr.,"CHANDIGARH,",CHANDIGARH,SKU:2X-3C0F-KNJE,100% Leather Elephant Shaped Piggy Coin Bank |...,1,₹449.00,NaN,unspecified,Delivered to buyer
3,405-3171677-9557154,2021-07-28 04:06:00+00:00,aciya,"DEVARAKONDA,",TELANGANA,SKU:AH-J3AO-R7DN,Pure 100% Leather Block Print Rectangular Jewe...,1,₹250.00,NaN,Cash On Delivery,Delivered to buyer
5,406-9292208-6725123,2021-06-17 21:12:00+00:00,Subinita,"HOWRAH,",WEST BENGAL,SKU:HH-FOWV-5YWO,Women's Trendy Pure Leather Clutch Purse | Lea...,1,₹200.00,NaN,unspecified,Delivered to buyer
6,404-5794317-7737924,2021-08-12 20:03:00+00:00,shailendra,"ORAI,",UTTAR PRADESH,SKU:TQ-OE6K-9DIK,Ultra Slim 100% Pure Leather Men's Wallet with...,1,₹649.00,NaN,Cash On Delivery,Returned to seller
9,171-7954707-4463549,2021-08-09 16:47:00+00:00,A.Jayaprada,"Bhilai,",CHHATTISGARH,SKU:NU-CKZ5-4O49,Pure Leather Sling Bag with Multiple Pockets a...,1,"₹1,099.00",NaN,unspecified,Delivered to buyer
24,403-7876698-8356365,2021-06-25 07:48:00+00:00,Yash,"MUMBAI,",MAHARASHTRA,SKU:3O-GBSM-TYZE,100% Leather Ganesh Ji Piggy Coin Bank | Block...,1,₹175.00,NaN,Cash On Delivery,Returned to seller
26,405-0695973-7365161,2021-07-22 09:32:00+00:00,Sailaja,"VISAKHAPATNAM,",ANDHRA PRADESH,SKU:AH-J3AO-R7DN,Pure 100% Leather Block Print Rectangular Jewe...,1,₹250.00,NaN,unspecified,Delivered to buyer
29,404-6883107-8347508,2021-08-04 20:16:00+00:00,chirag,"RAIA,",GOA,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,NaN,unspecified,Delivered to buyer
44,404-9914447-5578722,2021-08-06 09:16:00+00:00,Dipali,"Mumbai,",MAHARASHTRA,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,₹449.00,NaN,unspecified,Delivered to buyer
46,407-1526604-7803547,2021-08-13 12:02:00+00:00,Jolly,"GUWAHATI,",ASSAM,SKU:KL-7WAA-Z82I,Pure Leather Sling Bag with Multiple Pockets a...,1,"₹1,099.00",NaN,Cash On Delivery,Delivered to buyer
48,171-5705929-2195543,2021-08-16 21:27:00+00:00,John,"Ernakulam,",KERALA,SKU:NU-CKZ5-4O49,Pure Leather Sling Bag with Multiple Pockets a...,1,"₹1,099.00",NaN,Cash On Delivery,Delivered to buyer
51,402-5621007-4266725,2021-08-24 17:18:00+00:00,Tarek,"MUMBAI,",MAHARASHTRA,SKU:W4-JQ2J-ZUF2,100% Pure Leather Shantiniketan Clutch Purse: ...,1,₹399.00,NaN,unspecified,Delivered to buyer
52,404-7918321-6528342,2021-06-16 20:53:00+00:00,narendra,"KODAD,",TELANGANA,SKU:5B-NW9K-L3AO,Pure Leather Elephant Shaped Piggy Coin Bank |...,1,₹175.00,NaN,Cash On Delivery,Delivered to buyer
56,406-4504814-5756357,2021-06-16 22:35:00+00:00,Shamal,"BADLAPUR,",MAHARASHTRA,SKU:3O-GBSM-TYZE,Pure Leather Ganesh Piggy Bank | Money Bank fo...,1,₹175.00,NaN,unspecified,Delivered to buyer
59,171-1070115-6195560,2021-06-16 16:27:00+00:00,soumya,"THANE,",MAHARASHTRA,SKU:3O-GBSM-TYZE,Pure Leather Ganesh Piggy Bank | Money Bank fo...,1,₹175.00,NaN,unspecified,Delivered to buyer
60,407-5532335-4314768,2021-06-13 19:08:00+00:00,Pavithra,"POLLACHI,",TAMIL NADU,SKU:QV-PHXY-LGY8,Pure Leather Ganesh Piggy Bank | Money Bank fo...,1,₹175.00,NaN,unspecified,Delivered to buyer
63,403-3892336-2999521,2021-06-28 17:15:00+00:00,Ajay,"RAIPUR,",CHHATTISGARH,SKU:3O-GBSM-TYZE,100% Leather Ganesh Ji Piggy Coin Bank | Block...,1,₹349.00,NaN,unspecified,Delivered to buyer
68,407-4805322-7498725,2021-06-23 06:09:00+00:00,Velmurugan,"THISAYANVILAI,",TAMIL NADU,SKU:CR-6E69-UXFW,Pure Leather Elephant Shaped Piggy Coin Bank |...,1,₹449.00,NaN,unspecified,Delivered to buyer
71,402-4834476-0320360,2021-08-16 13:37:00+00:00,Abhishek,"KOLKATA,",WEST BENGAL,SKU:UR-WJJ0-I3TN,Pure 100% Leather Block Print Rectangular Jewe...,1,₹250.00,NaN,unspecified,Delivered to buyer
72,171-2479820-8391565,2021-07-29 18:04:00+00:00,Rajat,"New Delhi,",DELHI,SKU:RG-29TH-MROF,Bright and Colorful Handmade Shantiniketan Lea...,1,₹349.00,NaN,unspecified,Delivered to buyer
73,408-0358198-6688308,2021-07-21 19:40:00+00:00,S.,"Tuticorin,",TAMIL NADU,SKU:GP-RMI4-GJ6L,Bright & Colorful Shantiniketan Leather Piggy ...,1,₹549.00,NaN,Cash On Delivery,Delivered to buyer
76,406-6774677-4553965,2021-07-13 12:04:00+00:00,Priyanka,"HYDERABAD,",TELANGANA,SKU:5B-NW9K-L3AO,100% Leather Elephant Shaped Piggy Coin Bank |...,1,₹349.00,NaN,Cash On Delivery,Delivered to buyer
89,403-0124463-2966723,2021-07-26 08:15:00+00:00,Thanigaivel,"CHENNAI,",TAMIL NADU,SKU:QD-RNE2-2FH8,Colourful and Bright Peacock Shaped Piggy Coin...,1,₹449.00,NaN,unspecified,Delivered to buyer
90,403-5745034-5441137,2021-08-20 23:07:00+00:00,parul,"Surat,",GUJARAT,SKU:3V-FKXN-C4QJ,Handcrafted Women's Traditional Block Printed ...,1,"₹1,099.00",NaN,Cash On Delivery,Delivered to buyer
93,408-9069501-2731541,2021-08-18 11:10:00+00:00,shweta,"MUMBAI,",MAHARASHTRA,SKU:O9-OVS7-G9XK,Set of 2 Pure Leather Block Print Round Jewelr...,1,₹399.00,NaN,unspecified,Delivered to buyer
99,404-3621013-4015566,2021-08-08 07:08:00+00:00,roohi,"BENGALURU,",KARNATAKA,SKU:54-D265-B74K,Set of 2 Pure Leather Block Print Round Jewelr...,1,₹399.00,NaN,Cash On Delivery,Delivered to buyer

In [142]:
df["shipping_fee"]=df.groupby("sku")["shipping_fee"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

<ipython-input-142-ef121e66f7af>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["shipping_fee"]=df.groupby("sku")["shipping_fee"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))
<ipython-input-142-ef121e66f7af>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["shipping_fee"]=df.groupby("sku")["shipping_fee"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

#Analisis simple
Como se ve aun quedan datos nulos, sin embargo estos valores no se encuentran en el dataset a lo cual podemos rellenarlos con la media u otro metodo de tratar nulos

In [143]:
df.isnull().sum()

order_no         0
order_date       0
buyer            0
ship_city        0
ship_state       0
sku              0
description      0
quantity         0
item_total       3
shipping_fee    13
cod              0
order_status     0
dtype: int64

In [144]:
df.dtypes

order_no                     object
order_date      datetime64[ns, UTC]
buyer                string[python]
ship_city            string[python]
ship_state           string[python]
sku                  string[python]
description          string[python]
quantity                      int64
item_total                   object
shipping_fee                 object
cod                          object
order_status         string[python]
dtype: object

In [145]:
df.sample(2)

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
41,405-4776641-5401922,2021-10-01 14:18:00+00:00,Rathish,"AHMEDABAD,",GUJARAT,SKU:9S-GE8P-RIR4,Pure 100% Leather Block Print Rectangular Jewe...,1,₹250.00,₹84.96,unspecified,Delivered to buyer
151,171-8930811-8770760,2022-02-21 19:52:00+00:00,Shishir,"ALLAHABAD,",UTTAR PRADESH,SKU:4V-I7XD-JQVR,Bright and Colorful Shantiniketan Leather Elep...,1,₹349.00,₹60.18,unspecified,Delivered to buyer

#Instrucciones Final nulos
Como aun quedan datos nulos voy a verificar si no hay dato con valor de 0
luego si no hay valores con valor 0, reemplazar los nulos con 0, luego de eso pasamos a formato numerico las columnas, eliminando los caracteres y luego sacar la media de cada columna y remmplazar los valores que valgan 0 por la media, esto no es tan necesario con tan pocos datos pero es una demostracion, si es algo para una cantidad superior de datos podemos usar algo mas avanzado como simple imputer.

In [146]:
shiping_fee_zero = df[df["shipping_fee"] == '₹0.00'].shape
item_total_zero = df[df["item_total"] == '₹0.00'].shape

print(f"Nshiping_fee_zero: {shiping_fee_zero[0]}")
print(f"Nitem_total_zero: {item_total_zero[0]}")

Nshiping_fee_zero: 0
Nitem_total_zero: 0

In [147]:
df['shipping_fee'].fillna('₹0.00', inplace=True)
df['item_total'].fillna('₹0.00', inplace=True)

<ipython-input-147-f869494276de>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['shipping_fee'].fillna('₹0.00', inplace=True)
<ipython-input-147-f869494276de>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['item_total'].fillna('₹0.00', inplace=True)

In [105]:
df.isnull().sum()

order_no        0
order_date      0
buyer           0
ship_city       0
ship_state      0
sku             0
description     0
quantity        0
item_total      0
shipping_fee    0
cod             0
order_status    0
dtype: int64

In [ ]:
df['shipping_fee'] = df['shipping_fee'].str.replace('₹', '', regex=True).astype(float)
df['item_total'] = df['item_total'].str.replace(r'[₹,]', '', regex=True).astype(float)

In [155]:
df.dtypes

order_no                     object
order_date      datetime64[ns, UTC]
buyer                string[python]
ship_city            string[python]
ship_state           string[python]
sku                  string[python]
description          string[python]
quantity                      int64
item_total                  float64
shipping_fee                float64
cod                          object
order_status         string[python]
dtype: object

In [156]:
df.sample(5)

,order_no,order_date,buyer,ship_city,ship_state,sku,description,quantity,item_total,shipping_fee,cod,order_status
156,402-5940762-2914747,2022-01-02 15:01:00+00:00,Swathi,"Visakhapatnam,",ANDHRA PRADESH,SKU:0M-RFE6-443C,Set of 3 Pure Leather Block Print Round Jewelr...,1,475.0,84.96,unspecified,Delivered to buyer
84,406-9976360-8935534,2021-11-20 02:41:00+00:00,shilpin,"MUMBAI,",MAHARASHTRA,SKU:PG-WS6J-89DG,Bright and Colorful Shantiniketan Leather Elep...,1,449.0,84.96,unspecified,Delivered to buyer
131,171-5230421-3237921,2021-12-08 00:15:00+00:00,Geetika,"GURUGRAM,",HARYANA,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,449.0,84.96,unspecified,Delivered to buyer
122,404-7450458-9882702,2021-12-06 23:29:00+00:00,Arpita,"Thane District,",MAHARASHTRA,SKU:4V-I7XD-JQVR,Bright and Colorful Shantiniketan Leather Elep...,1,349.0,84.96,unspecified,Delivered to buyer
2,171-8103182-4289117,2021-11-28 22:20:00+00:00,yatipertin,"PASIGHAT,",ARUNACHAL PRADESH,SKU:DN-0WDX-VYOT,Women's Set of 5 Multicolor Pure Leather Singl...,1,449.0,60.18,unspecified,Delivered to buyer

#Final Nulos

Como se puede observar luego de todo este proceso ya no tendremos columnas con valores nulos, lo cual nos permitira trabajar con los datos de una mejor manera, ademas de haber dejado cada columna con su correspondiente tipo de dato

In [163]:
item_total_mean = df[df['item_total'] != 0]['item_total'].mean()
shiping_fee_mean = df[df['shipping_fee'] != 0]['shipping_fee'].mean()

print(f"shiping_fee_mean: {shiping_fee_mean}")
print(f"item_total_mean: {item_total_mean}")

shiping_fee_mean: 84.78822784810127
item_total_mean: 567.202380952381

In [165]:
df[df["shipping_fee"] == 0].shape

(13, 12)

In [167]:
df['shipping_fee'] = df['shipping_fee'].replace(0, shiping_fee_mean)
df[df["shipping_fee"] == 0].shape

(0, 12)

In [168]:
df[df["item_total"] == 0].shape

(3, 12)

In [169]:
df['item_total'] = df['item_total'].replace(0, item_total_mean)
df[df["item_total"] == 0].shape

(0, 12)

In [172]:
df.describe()

         quantity   item_total  shipping_fee
count  171.000000   171.000000    171.000000
mean     1.087719   567.202381     84.788228
std      0.445132   465.318570     24.613456
min      1.000000   175.000000     47.200000
25%      1.000000   399.000000     84.788228
50%      1.000000   449.000000     84.960000
75%      1.000000   524.000000     84.960000
max      4.000000  3897.000000    241.900000